#!/bin/bash

# This script runs rtorrent as a daemon service. Written by roog.
# More information at: http://bbs.archlinux.org/viewtopic.php?id=53395
# Requires rtorrent and dtach
# For installation:
#   1. Copy this file to /etc/rc.d/rtorrent
#   2. Change USER (below) to the desired username
#   3. Add the daemon to the array in /etc/rc.conf

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting rtorrent"
    su - USER -c 'dtach -n /tmp/rtorrent.dtach /usr/bin/rtorrent' &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon rtorrent
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping rtorrent"
    killall -s 2 rtorrent &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon rtorrent
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

